name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: get-cmake
      uses: lukka/get-cmake@v3.17.1
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v2.1
